version: '3'
services:
  tor-socks-proxy:
    container_name: tor-socks-proxy
    image: peterdavehello/tor-socks-proxy:latest
    ports:
      - "127.0.0.1:8853:53/udp"
      - "127.0.0.1:9150:9150/tcp"
    restart: unless-stopped

  instances:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
